from typing import Protocol
from .domain import Order


class OrderRepository(Protocol):
    def get(self, order_id: str) -> Order | None: ...
    def save(self, order: Order) -> None: ...


class OrderService(Protocol):
    def create(self, order_id: str, customer: str, total: str): ...
    def cancel(self, order_id: str): ...
    def get(self, order_id: str): ...
